import { Command } from 'commander';
import type { TimeEntrySource, TimeEntryStatus, TimeLogInput } from 'exponential-sdk';
import { getClient } from '../client/index.js';
import { handleError } from '../utils/errors.js';
import { readText, parseDate } from '../utils/input.js';
import { resolveWorkspaceId } from '../utils/resolve.js';
import {
  shouldUseJson,
  outputTimeLogJson,
  outputTimeLogPretty,
  outputTimeEntriesJson,
  outputTimeEntriesPretty,
  outputTimeBatchJson,
  outputTimeBatchPretty,
  outputTimeConfirmJson,
  outputTimeConfirmPretty,
} from '../utils/output.js';

interface GlobalOptions {
  json?: boolean;
  pretty?: boolean;
}

type LogSource = Exclude<TimeEntrySource, 'plugin'>;
const SOURCES: LogSource[] = ['manual', 'claude-desktop', 'agent-run'];
const STATUSES: TimeEntryStatus[] = ['PROPOSED', 'CONFIRMED'];

/**
 * The thing nobody guesses: with an external-agent key an entry is OWNED by
 * the agent's owner, the agent is recorded as author, and it is always
 * PROPOSED — it shows on the owner's /time with a "proposed" chip and stays
 * out of the Action's spent time until the owner confirms the day (ADR-0061).
 */
const OWNERSHIP_NOTE =
  'Run with an external-agent key, the entry belongs to the agent\'s OWNER and is always PROPOSED; a personal token logs your own time, CONFIRMED by default.';

function parseSource(value: string): LogSource {
  const lower = value.toLowerCase() as LogSource;
  if (!SOURCES.includes(lower)) {
    throw new Error(`Invalid source "${value}". Use one of: ${SOURCES.join(', ')}.`);
  }
  return lower;
}

function parseStatus(value: string): TimeEntryStatus {
  const upper = value.toUpperCase() as TimeEntryStatus;
  if (!STATUSES.includes(upper)) {
    throw new Error(`Invalid status "${value}". Use one of: ${STATUSES.join(', ')}.`);
  }
  return upper;
}

/** One entry in a `--from-file` batch, in JSON. `from`/`to`/`ref`/`action` mirror the flags. */
interface BatchItem {
  actionId?: unknown;
  action?: unknown;
  startedAt?: unknown;
  from?: unknown;
  endedAt?: unknown;
  to?: unknown;
  source?: unknown;
  status?: unknown;
  sourceRef?: unknown;
  ref?: unknown;
  note?: unknown;
}

/** Every key a `--from-file` entry may carry; anything else is a typo. */
const BATCH_ITEM_KEYS = new Set<keyof BatchItem>([
  'actionId',
  'action',
  'startedAt',
  'from',
  'endedAt',
  'to',
  'source',
  'status',
  'sourceRef',
  'ref',
  'note',
]) as Set<string>;

export function parseBatchFile(raw: string): BatchItem[] {
  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch (error) {
    throw new Error(
      `--from-file must be JSON: ${error instanceof Error ? error.message : String(error)}`,
    );
  }
  const items = Array.isArray(parsed)
    ? parsed
    : typeof parsed === 'object' &&
        parsed !== null &&
        Array.isArray((parsed as { entries?: unknown }).entries)
      ? (parsed as { entries: unknown[] }).entries
      : null;
  if (!items) {
    throw new Error('--from-file must contain a JSON array of entries, or {"entries": [...]}.');
  }
  if (items.length === 0) {
    throw new Error('--from-file contained no entries.');
  }
  return items.map((item, i) => {
    if (typeof item !== 'object' || item === null) {
      throw new Error(`Entry[${i}] is not an object.`);
    }
    const entry = item as BatchItem;
    // These files are generated by the Daily worklog. A key this reader
    // doesn't know is a typo or a wrong field name, and dropping it silently
    // would log the entry without the data its author meant to attach.
    const unknown = Object.keys(entry).filter((key) => !BATCH_ITEM_KEYS.has(key));
    if (unknown.length > 0) {
      throw new Error(
        `Entry[${i}] has unknown field(s): ${unknown.join(', ')}. Accepted: ${[...BATCH_ITEM_KEYS].join(', ')}.`,
      );
    }
    return entry;
  });
}

function optionalString(value: unknown, label: string, index: number): string | undefined {
  if (value === undefined || value === null) return undefined;
  if (typeof value !== 'string') throw new Error(`Entry[${index}].${label} must be a string.`);
  return value;
}

/** Turn a batch entry into the SDK input, with the flags as defaults. */
export function batchItemToInput(
  item: BatchItem,
  index: number,
  defaults: Partial<TimeLogInput>,
): TimeLogInput {
  const actionId = optionalString(item.actionId ?? item.action, 'actionId', index) ?? defaults.actionId;
  const from = optionalString(item.startedAt ?? item.from, 'startedAt', index);
  const to = optionalString(item.endedAt ?? item.to, 'endedAt', index);
  const startedAt = from !== undefined ? parseDate(from) : defaults.startedAt;
  const endedAt = to !== undefined ? parseDate(to) : defaults.endedAt;
  if (!actionId) throw new Error(`Entry[${index}] needs an "actionId" (or the --action flag).`);
  if (!startedAt || !endedAt) {
    throw new Error(`Entry[${index}] needs "startedAt" and "endedAt" (or --from and --to).`);
  }
  const source = optionalString(item.source, 'source', index);
  const status = optionalString(item.status, 'status', index);
  return {
    actionId,
    startedAt,
    endedAt,
    source: source !== undefined ? parseSource(source) : defaults.source,
    status: status !== undefined ? parseStatus(status) : defaults.status,
    sourceRef: optionalString(item.sourceRef ?? item.ref, 'sourceRef', index) ?? defaults.sourceRef,
    note: optionalString(item.note, 'note', index) ?? defaults.note,
  };
}

export function createTimeCommand(): Command {
  const time = new Command('time').description(
    `Time entries — log the day's work and list it. ${OWNERSHIP_NOTE}`,
  );

  time
    .command('log')
    .description(
      [
        'Log one completed entry with explicit bounds; the running Timer is never touched.',
        'With --ref the write is idempotent per owner: a re-run updates a PROPOSED entry and leaves a CONFIRMED one alone.',
        'Bulk: --from-file <path|-> takes a JSON array of entries; the other flags become its defaults.',
        OWNERSHIP_NOTE,
      ].join(' '),
    )
    .option('-a, --action <id>', 'Action CUID the time was spent on')
    .option('--from <iso>', 'Start, e.g. 2026-09-11T09:22')
    .option('--to <iso>', 'End, e.g. 2026-09-11T10:30')
    .option('--source <source>', `${SOURCES.join(', ')} (default: manual)`)
    .option('--status <status>', 'PROPOSED or CONFIRMED (ignored under an agent key: always PROPOSED)')
    .option('--ref <sourceRef>', 'Idempotency key, e.g. claude-session:<sessionId>#<segment>')
    .option('--note <text>', 'One line shown in the day view and list row')
    .option('--from-file <path>', 'Bulk log from a JSON array of entries ("-" = stdin)')
    .action(
      async (
        options: {
          action?: string;
          from?: string;
          to?: string;
          source?: string;
          status?: string;
          ref?: string;
          note?: string;
          fromFile?: string;
        },
        cmd: Command,
      ) => {
        const globalOpts = cmd.optsWithGlobals() as GlobalOptions;
        const useJson = shouldUseJson(globalOpts.json, globalOpts.pretty);
        try {
          const defaults: Partial<TimeLogInput> = {
            actionId: options.action,
            startedAt: parseDate(options.from),
            endedAt: parseDate(options.to),
            source: options.source ? parseSource(options.source) : undefined,
            status: options.status ? parseStatus(options.status) : undefined,
            sourceRef: options.ref,
            note: options.note,
          };
          const client = getClient();

          if (options.fromFile) {
            if (options.ref !== undefined) {
              throw new Error(
                '--ref is per-entry: a shared sourceRef would make every entry overwrite the last. Put "sourceRef" on each entry in --from-file instead.',
              );
            }
            const items = parseBatchFile(readText(undefined, options.fromFile)!);
            const inputs: Array<TimeLogInput | Error> = items.map((item, i) => {
              try {
                return batchItemToInput(item, i, defaults);
              } catch (error) {
                return error instanceof Error ? error : new Error(String(error));
              }
            });
            // Sequential on purpose: a partial failure has to name which
            // entry failed rather than collapsing into one rejected batch.
            const results = [];
            for (const [index, input] of inputs.entries()) {
              if (input instanceof Error) {
                results.push({ index, success: false, error: input.message });
                continue;
              }
              const [result] = await client.time.logBatch([input]);
              results.push({ ...result!, index });
            }
            // Anything short of "everything was logged" is a non-zero exit,
            // so a pipeline can't mistake a partial write for success.
            if (results.some((r) => !r.success)) process.exitCode = 1;
            if (useJson) outputTimeBatchJson(results);
            else outputTimeBatchPretty(results);
            return;
          }

          if (!defaults.actionId) throw new Error('Pass --action <id>, or --from-file <path|-> for a batch.');
          if (!defaults.startedAt || !defaults.endedAt) throw new Error('Pass both --from <iso> and --to <iso>.');
          if (defaults.endedAt.getTime() <= defaults.startedAt.getTime()) {
            throw new Error('--to must be after --from.');
          }
          const result = await client.time.log(defaults as TimeLogInput);
          if (useJson) outputTimeLogJson(result);
          else outputTimeLogPretty(result);
        } catch (error) {
          handleError(error);
        }
      },
    );

  time
    .command('list')
    .description("One day's entries for the signed-in user, oldest first, each with its PROPOSED/CONFIRMED status")
    .requiredOption('-d, --date <YYYY-MM-DD>', 'The day (local time)')
    .option('-w, --workspace <slug|id>', 'Only entries in this workspace (default: all)')
    .option('--proposed', 'Only PROPOSED entries')
    .action(async (options: { date: string; workspace?: string; proposed?: boolean }, cmd: Command) => {
      const globalOpts = cmd.optsWithGlobals() as GlobalOptions;
      const useJson = shouldUseJson(globalOpts.json, globalOpts.pretty);
      try {
        if (!/^\d{4}-\d{2}-\d{2}$/.test(options.date)) {
          throw new Error(`--date must be YYYY-MM-DD, got "${options.date}".`);
        }
        const client = getClient();
        const workspaceId = options.workspace
          ? await resolveWorkspaceId(client, options.workspace)
          : undefined;
        let entries = await client.time.list(options.date, workspaceId);
        if (options.proposed) entries = entries.filter((e) => e.status === 'PROPOSED');
        if (useJson) outputTimeEntriesJson(entries, options.date);
        else outputTimeEntriesPretty(entries, options.date);
      } catch (error) {
        handleError(error);
      }
    });

  time
    .command('confirm')
    .description(
      "Confirm a day: every PROPOSED entry of yours that starts that day becomes CONFIRMED and the Actions' spent time moves. Human only — run it with your personal credentials; an agent key is refused.",
    )
    .requiredOption('-d, --date <YYYY-MM-DD>', 'The day (local time)')
    .option('-w, --workspace <slug|id>', 'Only entries in this workspace (default: all)')
    .action(async (options: { date: string; workspace?: string }, cmd: Command) => {
      const globalOpts = cmd.optsWithGlobals() as GlobalOptions;
      const useJson = shouldUseJson(globalOpts.json, globalOpts.pretty);
      try {
        if (!/^\d{4}-\d{2}-\d{2}$/.test(options.date)) {
          throw new Error(`--date must be YYYY-MM-DD, got "${options.date}".`);
        }
        const client = getClient();
        const workspaceId = options.workspace
          ? await resolveWorkspaceId(client, options.workspace)
          : undefined;
        const result = await client.time.confirmDay(options.date, workspaceId);
        if (useJson) outputTimeConfirmJson(result, options.date);
        else outputTimeConfirmPretty(result, options.date);
      } catch (error) {
        handleError(error);
      }
    });

  return time;
}

